//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int User_Id { get; set; }
        [Required(ErrorMessage = "Please enter user name.")]
        [Display(Name = "User Name")]
        public string User_name { get; set; }
        [Required(ErrorMessage = "Please enter password.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string User_Type { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
