//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int User_Type_Id { get; set; }
        public int User_Type { get; set; }
        public string User_Type_Name { get; set; }
    }
}
